#!/bin/bash
#   _____       _             _    ______       _ _     _           
#  /  ___|     (_)           | |   | ___ \     (_) |   | |          
#  \ `--. _ __  _  __ _  ___ | |_  | |_/ /_   _ _| | __| | ___ _ __ 
#   `--. \ '_ \| |/ _` |/ _ \| __| | ___ \ | | | | |/ _` |/ _ \ '__|
#  /\__/ / |_) | | (_| | (_) | |_  | |_/ / |_| | | | (_| |  __/ |   
#  \____/| .__/|_|\__, |\___/ \__| \____/ \__,_|_|_|\__,_|\___|_|   
#        | |       __/ |                                            
#        |_|      |___/                                             
#VERSION 1.0
#Installs a spigot server with some settings preconfigured by Thomas James
#who is probably the most notorious minecraft dweeb at GCU, don't @ me

#Some important notes:
#This program doesn't set your server to a static IP address, which is ideal for persistent installations, so make sure you use ifconfig to find/set your IP.
#You need to set how much RAM your server is going to use manually, see below.

	#Updates and prerequisite programs

yum update -y
yum install wget git java-1.8.0-openjdk -y

	#Directory creation

mkdir /home/centos/buildtools/
mkdir /home/centos/spigot/
ln -s /home/centos/spigot/ Desktop/ServerFolder
cd /home/centos/buildtools/

	#Download/install of BuildTools -- note: make sure the environment has >1.2 GB of RAM

wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
java -jar BuildTools.jar --rev 1.12.2
mv spigot-1.12.2.jar /home/centos/spigot/spigot-1.12.2.jar
cd /home/centos/spigot/
echo "eula=true" >> eula.txt

	#opening the minecraft server port

iptables -I INPUT -p tcp --dport 25565 --syn -j ACCEPT

	#Initialize server first-time: more commands than usual will run in the first instance.
	#(Ideally there's going to be another command to just run the server, without all the setup here)
	#Be sure to replace the "XG" here with however many dedodated wam's the final server should have

java -Xmx2G -Xms2G -XX:+UseConcMarkSweepGC -jar spigot-1.12.2.jar


	


